version: '1'

services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./src/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
  web:
    build: ./src/web
    container_name: pythonWeb
    ports:
      - "5004:5004"