version: '3'
services:
  bind:
    image: ubuntu/bind9:latest
    ports:
      - "53:53"
    volumes:
      - ./src/bind/named.conf:etc/bind/named.conf
      - ./src/bind/named.conf.options:/etc/bind/named.conf.options
      - ./src/bind/named.conf.local:/etc/bind/named.conf.local
      - ./src/bind/named.conf.default-zones:/etc/bind/named.conf.default-zones
      - ./src/bind/domain:/etc/bind/domain
  # nginx:
  #   image: nginx:latest
  #   ports:
  #     - 80:80
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  #   depends_on:
  #     - bind9
  #     - web
  # web:
  #   build: ./src/web
  #   ports:
  #     - "5004:5004"